version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_php_app
    environment:
      - APPLICATION_ENV=development
    ports:
    - "8080:80" # Map port 8080 on the host to port 80 in the container
    networks:
      - shared-local-network
      
networks:
  shared-local-network:
    driver: bridge