version: "3.8"
services:
  frontend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/var/www/html/public
      - ./odbc-driver-configs:/etc
    container_name: frontend_php_app
    environment:
      - APPLICATION_ENV=development
    ports:
    - "8080:80" # Map port 8080 on the host to port 80 in the container
    networks:
      - shared-local-network
      
networks:
  shared-local-network:
    driver: bridge